[package]
name = "finite-state-machine"
description = "A type and trait based finite state machine macro"
license = "MIT"
version = "0.1.1"
edition = "2021"

[features]
verbose = []

[dependencies]
paste = "1.0.12"
